AWSTemplateFormatVersion: '2010-09-09'
Description: CI/CD pipeline for OneDayGames leaderboard service using CodePipeline and CodeBuild

Parameters:
  PipelineName:
    Type: String
    Default: LeaderboardPipeline
  SourceConnectionArn:
    Type: String
    Description: CodeStar Connections ARN for the repository
  SourceRepositoryId:
    Type: String
    Description: e.g. owner/repo for GitHub
  SourceBranch:
    Type: String
    Default: main
  ArtifactBucketName:
    Type: String
    Description: S3 bucket for pipeline artifacts
  DeployStackName:
    Type: String
    Default: leaderboard-service
  SamConfigEnv:
    Type: String
    Default: prod

Resources:
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
      Policies:
        - PolicyName: PipelineExtra
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactBucketName}
                  - !Sub arn:aws:s3:::${ArtifactBucketName}/*
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: '*'

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
      Policies:
        - PolicyName: BuildExtra
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:DeleteChangeSet
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactBucketName}
                  - !Sub arn:aws:s3:::${ArtifactBucketName}/*
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                Resource: '*'
              - Effect: Allow
                Action:
                  - dynamodb:DescribeTable
                  - dynamodb:CreateTable
                  - dynamodb:UpdateTable
                  - dynamodb:DeleteTable
                Resource: '*'

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${PipelineName}-build'
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: STACK_NAME
            Value: !Ref DeployStackName
          - Name: SAM_CONFIG_ENV
            Value: !Ref SamConfigEnv
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 30
      Cache:
        Type: NO_CACHE
      QueuedTimeoutInMinutes: 60
      BadgeEnabled: false
      BuildSpec: |
        version: 0.2
        phases:
          install:
            runtime-versions:
              nodejs: 20
            commands:
              - cd aws/leaderboard
              - npm ci
          pre_build:
            commands:
              - cd aws/leaderboard
              - npm test
          build:
            commands:
              - cd aws/leaderboard
              - npm run build
              - sam build
              - sam deploy --stack-name $STACK_NAME --no-confirm-changeset --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --config-env $SAM_CONFIG_ENV
        artifacts:
          files:
            - '**/*'

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref PipelineName
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucketName
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref SourceConnectionArn
                FullRepositoryId: !Ref SourceRepositoryId
                BranchName: !Ref SourceBranch
              OutputArtifacts:
                - Name: SourceOutput
              RunOrder: 1
        - Name: BuildAndDeploy
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref BuildProject
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              RunOrder: 1

Outputs:
  PipelineNameOut:
    Value: !Ref PipelineName
    Description: Name of the created pipeline
